---
title: "Central India Connectivity Synthesis"
author: "Jay Schoen"
output: pdf_document
editor_options:
  chunk_output_type: console
---


```{r}
library(sp)
library(sf)
library(raster)
library(tidyverse)
library(rgeos)
library(rgdal)
library(scales)
```

# Setup
```{r}
# World Mercator projection
merc <- "+init=epsg:3395"

# All layers union shape
tiger_lyrs_shp <- readOGR("spatial_layers/tiger_layers_shape.shp") 

# PA shapefile
PA_shp <- readOGR("Buffer node analysis/PA_node.shp") %>%
  spTransform(merc) 

# Template raster
template250 <- raster(resolution = c(250, 250), ext = extent(tiger_lyrs_shp), crs = merc)
# template1k <- raster(resolution = c(1000, 1000), ext = extent(tiger_lyrs_shp), crs = merc)
```

# Aligning rasters
```{r}
dutta.raw <- raster("DATA/DUTTA/resistance_Sc1b_W3.tif")
mondal.raw <- raster("DATA/Indranil/indranil_250m_filled.tif")
reddy.raw <- raster("DATA/REDDY/Anuradha_sam_tiger_resistance_and_connectivity/resist1.tif", 
                    crs = "+init=epsg:32644")
thatte.raw <- raster("DATA/THATTE/Copy of optim_tig_forCircuitscape_m_unified.tif") 
yumnam.raw <- raster("DATA/JHALA/Resistance1/Resistance/resist_final/w001001.adf") 

lyr_names <- c("Dutta", "Mondal", "Reddy", "Thatte", "Yumnam")

# Projecting all rasters to World Mercator, 250m res (using bilinear interpolation), tiger layers shape extent 
# Aligning and preparing rasters for stacking and further analysis
dutta_res <- dutta.raw %>%
  projectRaster(template250) # bilinear interpolation is default method in "projectRaster"

mondal_res <- mondal.raw %>%
  projectRaster(template250) 

reddy_res <- reddy.raw %>%
  projectRaster(template250)

thatte_res <- thatte.raw 
thatte_res[thatte_res< 0] <- NA # classify <0 values as NA 
thatte_res <- thatte_res %>%
  projectRaster(template250) 

yumnam_res <- yumnam.raw
yumnam_res <- yumnam_res %>%
  projectRaster(template250) 
yumnam_res[yumnam_res >1] <- NA # removing erroneous >1 values left over from interpolation
yumnam_res[yumnam_res <=0] <- 1e-7 # setting negative areas to 1e-7 (lowest resistance)



layers <- c(dutta_res, mondal_res, reddy_res, thatte_res, yumnam_res) %>%
  `names<-` (lyr_names)
lapply(layers, summary)


# Visualizing Individually
india <- readOGR("spatial_layers/projects.datameet.org/States/Admin2.shp") %>%
  spTransform("+init=epsg:3395")

plot(india, main = "Dutta et al. (2018)"); axis(1); axis(2); plot(dutta_res, add = T)
plot(india, main = "Mondal et al. (2016)"); axis(1); axis(2); plot(mondal_res, add = T)
plot(india, main = "Reddy et al. (2015)"); axis(1); axis(2); plot(reddy_res, add = T)
plot(india, main = "Thatte et al. (2018)"); axis(1); axis(2); plot(thatte_res, add = T)
plot(india, main = "Yumnam et al. (2014)"); axis(1); axis(2); plot(yumnam_res, add = T)


# Stacking and clipping/masking
stack_res <- stack(layers) %>%
  crop(tiger_lyrs_shp) %>%
  mask(tiger_lyrs_shp) %>%
  `names<-` (str_glue("{lyr_names}_res"))

plot(stack_res)

## Exporting as .tif and .ascii (for Circuitscape)

# writeRaster(stack_res, file.path("analysis_final/res/", names(stack_res)), bylayer = T, format = "GTiff", overwrite = T)
# writeRaster(stack_res, file.path("analysis_final/res/", names(stack_res)), bylayer = T, format = "ascii", overwrite = T)
```


